import type { Metadata } from 'next'

import './globals.css'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/providers/theme-provider'
import { numericFont, primaryFont } from '@/lib/fonts'
import AuthProvider from '@/providers/AuthProvider'
import { Toaster } from 'sonner'

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// })
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fa-IR" dir="rtl" suppressHydrationWarning>
      <AuthProvider>
        <body
          className={` ${primaryFont.className} ${numericFont.className} adad min-h-screen antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Toaster richColors position="bottom-left" />
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  )
}
